kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80   # Ingress Controller container port
        hostPort: 80        # Windows Host Port
        protocol: TCP
